codecov:
  notify:
    wait_for_ci: false

coverage:
  status:
    project:
      default:
        target: 20%
        if_ci_failed: success
    patch:
      default:
        target: 80%
        threshold: 100%
        if_ci_failed: success

comment:
  layout: "diff"